### ISSUE TITLE
Can not make request after migrating to V6 from V5

### ISSUE THREAD

**Issue by talalong** [microsoftgraph/msgraph-sdk-java#2236]
I followed the migration instruction [here](https://github.com/microsoftgraph/msgraph-sdk-java/blob/main/docs/upgrade-to-v6.md). After the migration I can not make any request to Azure B2C.
This is the error I am getting:
> java.lang.NoSuchMethodError: 'com.azure.core.credential.TokenRequestContext com.azure.core.credential.TokenRequestContext.setCaeEnabled(boolean)'
	at com.microsoft.kiota.authentication.AzureIdentityAccessTokenProvider.getAuthorizationToken(AzureIdentityAccessTokenProvider.java:161) ~[microsoft-kiota-authentication-azure-1.7.0.jar:na]
	at com.microsoft.kiota.authentication.BaseBearerTokenAuthenticationProvider.authenticateRequest(BaseBearerTokenAuthenticationProvider.java:46) ~[microsoft-kiota-abstractions-1.7.0.jar:na]
	at com.microsoft.kiota.http.OkHttpRequestAdapter.getHttpResponseMessage(OkHttpRequestAdapter.java:710) ~[microsoft-kiota-http-okHttp-1.7.0.jar:na]
	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:275) ~[microsoft-kiota-http-okHttp-1.7.0.jar:na]
	at com.microsoft.graph.users.item.UserItemRequestBuilder.get(UserItemRequestBuilder.java:761) ~[microsoft-graph-6.20.0.jar:na]
	at com.microsoft.graph.users.item.UserItemRequestBuilder.get(UserItemRequestBuilder.java:747) ~[microsoft-graph-6.20.0.jar:na]

I also try the latest `kiota version 1.8.x` but it did not help.
What am I missing here?

Here are the changes regarding the authentication:
```
@Configuration
public class GraphConfiguration {
    private static final String SCOPE = "https://graph.microsoft.com/.default";

    @Bean
    public GraphServiceClient graphClient(AadAuthenticationProperties aadAuthenticationProperties) throws Exception {
        ClientSecretCredential credential = new ClientSecretCredentialBuilder()
                .clientId(aadAuthenticationProperties.getCredential().getClientId())
                .clientSecret(aadAuthenticationProperties.getCredential().getClientSecret())
                .tenantId(aadAuthenticationProperties.getProfile().getTenantId())
                .build();

        if (null == scopes || null == credential) {
            throw new Exception("Unexpected error while initializing GraphServiceClient");
        }

        return new GraphServiceClient(credential, SCOPE);
    }
}
```

And the call looks like this:

```
public User getLoggedInUserInfo() {
        return graphServiceClient
                .me()
                .get();
    }
```

**Comment by talalong** [comment]
I think that's a bug because I switched to V6.13 and the error was gone. Please confirm this.

**Comment by Ndiritu** [comment]
Hi @talalong, please confirm that you've included a dependency on [azure-identity](https://central.sonatype.com/artifact/com.azure/azure-identity) alongside this library as shown in the [README](https://github.com/microsoftgraph/msgraph-sdk-java?tab=readme-ov-file#11-install-via-gradle)

**Comment by talalong** [comment]
Hi @Ndiritu,
I installed the dependency Azure-identity 1.11.0, but it didn't help. I am getting the same error.
> java.lang.NoSuchMethodError: 'com.azure.core.credential.TokenRequestContext com.azure.core.credential.TokenRequestContext.setCaeEnabled(boolean)'
	at com.microsoft.kiota.authentication.AzureIdentityAccessTokenProvider.getAuthorizationToken(AzureIdentityAccessTokenProvider.java:161) ~[microsoft-kiota-authentication-azure-1.8.0.jar:na]
	at com.microsoft.kiota.authentication.BaseBearerTokenAuthenticationProvider.authenticateRequest(BaseBearerTokenAuthenticationProvider.java:46) ~[microsoft-kiota-abstractions-1.8.0.jar:na]
	at com.microsoft.kiota.http.OkHttpRequestAdapter.getHttpResponseMessage(OkHttpRequestAdapter.java:710) ~[microsoft-kiota-http-okHttp-1.8.0.jar:na]
	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:275) ~[microsoft-kiota-http-okHttp-1.8.0.jar:na]
	at com.microsoft.graph.users.item.UserItemRequestBuilder.get(UserItemRequestBuilder.java:761) ~[microsoft-graph-6.24.0.jar:na]

**Comment by Ndiritu** [comment]
@talalong  Interesting. I'm unable to reproduce this behavior.
Please share your project's dependency tree: `./gradlew dependencies` or `mvn dependency:tree`
