### ISSUE TITLE
com.microsoft.graph:microsoft-graph from 5.6.0 to 6.14.0 #155

### ISSUE THREAD

**Issue by criskkan1** [microsoftgraph/msgraph-sdk-java#2158]
I have upgraded [my ](com.microsoft.graph:microsoft-graph from 5.6.0 to 6.14.0  from parent POM

Now when trying to build the the entire project I am getting these errors from on of my child module "msgraph adapter" 

**[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project host-service-msgraph-adapter: Compilation failure: Compilation failure:
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/mapper/response/MSGraphSdkResponseMapper.java:[41,36] package com.microsoft.graph.reques
ts does not exist
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/mapper/response/MSGraphSdkResponseMapper.java:[42,36] package com.microsoft.graph.reques
ts does not exist
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/util/GraphAuthProvider.java:[4,42] package com.microsoft.graph.authentication does not e
xist
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/util/GraphAuthProvider.java:[13,43] cannot find symbol
[ERROR]   symbol: class IAuthenticationProvider
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/mapper/response/MSGraphSdkResponseMapper.java:[77,5] cannot find symbol
[ERROR]   symbol:   class GraphServiceClient
[ERROR]   location: class com.cbre.host.msgraph.mapper.response.MSGraphSdkResponseMapper
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/config/SdkCustomRetryAfterBackOffPolicy.java:[4,32] package com.microsoft.graph.http doe
s not exist
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/config/SdkCustomRetryAfterBackOffPolicy.java:[84,56] cannot find symbol
[ERROR]   symbol:   class GraphServiceException
[ERROR]   location: class com.cbre.host.msgraph.config.SdkCustomRetryAfterBackOffPolicy
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/service/helper/SdkServiceHelperAsync.java:[12,32] cannot find symbol
[ERROR]   symbol:   class ClientException
[ERROR]   location: package com.microsoft.graph.core
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/service/helper/SdkServiceHelperAsync.java:[13,32] package com.microsoft.graph.http does 
not exist
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/service/helper/SdkServiceHelperAsync.java:[14,34] cannot find symbol
[ERROR]   symbol:   class CalendarGetScheduleParameterSet
[ERROR]   location: package com.microsoft.graph.models
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/service/helper/SdkServiceHelperAsync.java:[16,36] package com.microsoft.graph.requests d
oes not exist
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/service/helper/SdkServiceHelperAsync.java:[17,36] package com.microsoft.graph.requests d
oes not exist
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/service/helper/SdkServiceHelperAsync.java:[40,5] cannot find symbol
[ERROR]   symbol:   class GraphServiceClient
[ERROR]   location: class com.cbre.host.msgraph.service.helper.SdkServiceHelperAsync
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/exception/ExceptionHandlerAdvice.java:[6,32] cannot find symbol
[ERROR]   symbol:   class ClientException
[ERROR]   location: package com.microsoft.graph.core
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/exception/ExceptionHandlerAdvice.java:[7,32] package com.microsoft.graph.http does not e
xist
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/exception/ExceptionHandlerAdvice.java:[140,63] cannot find symbol
[ERROR]   symbol:   class GraphServiceException
[ERROR]   location: class com.cbre.host.msgraph.exception.ExceptionHandlerAdvice
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/exception/ExceptionHandlerAdvice.java:[161,57] cannot find symbol
[ERROR]   symbol:   class ClientException
[ERROR]   location: class com.cbre.host.msgraph.exception.ExceptionHandlerAdvice
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/util/GraphUtils.java:[11,35] package com.microsoft.graph.options does not exist
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/util/GraphUtils.java:[189,24] cannot find symbol
[ERROR]   symbol:   class QueryOption
[ERROR]   location: class com.cbre.host.msgraph.util.GraphUtils
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/config/SdkCustomRetryPolicy.java:[4,32] package com.microsoft.graph.http does not exist 
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/exception/ExceptionHandlerAdvice.java:[139,23] cannot find symbol
[ERROR]   symbol:   class GraphServiceException
[ERROR]   location: class com.cbre.host.msgraph.exception.ExceptionHandlerAdvice
[ERROR] /C:/Users/ckadima/Downloads/Doc/Develop/Security/host-service-java/host-service-msgraph-adapter/src/main/java/com/cbre/host/msgraph/exception/ExceptionHandlerAdvice.java:[160,23] cannot find symbol
[ERROR]   symbol:   class ClientException
[ERROR]   location: class com.cbre.host.msgraph.exception.ExceptionHandlerAdvice
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException**

My child has dependency  without the version because it's depending on the parent. 
it worked fine with  5.6.0  

**Parent**: 
<dependency> 
  <groupId>com.microsoft.graph</groupId>
  <artifactId>microsoft-graph</artifactId>
<version>6.14.0</version>
</dependency>

**Child**: 
<dependency> 
  <groupId>com.microsoft.graph</groupId>
  <artifactId>microsoft-graph</artifactId>
</dependency>

Can you help?

**Comment by criskkan1** [comment]
the new version is missing requests  folder
![image](https://github.com/user-attachments/assets/58a886ff-91b7-484d-9cbb-ef324958a060)

**Comment by Ndiritu** [comment]
Hi @criskkan1
Thank you for reaching out and uprading to version 6!
There are a couple of breaking changes between v5 and v6.

We have an upgrade guide [here](https://github.com/microsoftgraph/msgraph-sdk-java/blob/main/docs/upgrade-to-v6.md) and would suggest you reference code samples on how to create a client & make requests via our [reference docs](https://learn.microsoft.com/en-us/graph/sdks/create-client?view=graph-rest-1.0&tabs=java).

Please let us know if anything can be clarified better on the docs.

**Comment by criskkan1** [comment]
which java version is compatible to 6.14.0?

**Comment by Ndiritu** [comment]
> which java version is compatible to 6.14.0?

We support [Java 8+](https://github.com/microsoftgraph/msgraph-sdk-java?tab=readme-ov-file#7-supported-java-versions)

**Comment by criskkan1** [comment]
So much change were made on the new version, I can't found several folders to map below are my codes   



@Component
public class MSGraphSdkResponseMapper {

    private static final Logger LOGGER = LoggerFactory.getLogger(MSGraphSdkResponseMapper.class);

    GraphAuthProvider authProvider;

    GraphServiceClient<?> graphClient;

    @Autowired
    AdapterSdkRequestMapper adaptorSdkRequestMapper;

    @PostConstruct
    public void init() {
        authProvider = new GraphAuthProvider(null);
        graphClient = GraphServiceClient.builder().authenticationProvider(authProvider).buildClient();
    }

    public List<Availability> parseResourceAvailabilityRes(List<ScheduleInformation> scheduleInformations,
            ResourceAvailabilityRequest request) throws HostException {
        try {

            if (!CollectionUtils.isEmpty(scheduleInformations)) {
                Integer availabilityInterval = Integer.valueOf(request.getAvailabilityViewInterval());

                List<Availability> availabilityList = new ArrayList<>();

                for (ScheduleInformation schedule : scheduleInformations) {
                    if (Objects.isNull(schedule.scheduleItems)) {
                        continue;
                    }
                    String startTime = request.getStartTime().getDateTime();
                    String endTime = request.getEndTime().getDateTime();
                    Availability availability = new Availability();
                    List<AvailabilitySchedule> schedulesList = new ArrayList<>();

                    for (char status : schedule.availabilityView.toCharArray()) {
                        AvailabilitySchedule availabilitySchedule = new AvailabilitySchedule();

                        String availabilityStatus = getAvailabilityStatus(status);

                        com.cbre.host.msgraph.dto.DateTimeTimeZone start =
                                new com.cbre.host.msgraph.dto.DateTimeTimeZone();
                        start.setDateTime(startTime);
                        start.setTimeZone(GraphConstants.DEFAULT_TIMEZONE);

                        com.cbre.host.msgraph.dto.DateTimeTimeZone end =
                                new com.cbre.host.msgraph.dto.DateTimeTimeZone();
                        String endTimeSlot = addTime(startTime, availabilityInterval);
                        end.setDateTime(endTimeSlot);
                        end.setTimeZone(GraphConstants.DEFAULT_TIMEZONE);

                        availabilitySchedule.setStart(start);
                        availabilitySchedule.setEnd(end);
                        availabilitySchedule.setStatus(availabilityStatus);

                        // Add if schedule's end time is within requested end time
                        Date endDate = GraphUtils.convertISOFormatStringToDate(endTime);
                        Date scheduleEndDate = GraphUtils.convertISOFormatStringToDate(endTimeSlot);
                        if (scheduleEndDate.before(endDate) || scheduleEndDate.equals(endDate)) {
                            schedulesList.add(availabilitySchedule);
                        }

                        startTime = endTimeSlot;
                    }
                    availability.setScheduleId(schedule.scheduleId);
                    availability.setScheduleItems(schedulesList);
                    availabilityList.add(availability);
                }
                return availabilityList;
            }
        } catch (Exception e) {
            LOGGER.error("Error occured while parsing resourse-availability response:{}:{}", e.getMessage(),
                    e.getCause());
            throw new HostException(e.getMessage(), e.getCause());
        }

        return Collections.emptyList();
    }

    /**
     * Method to get status corresponding to availability code
     *
     * @param char
     * @return String
     */
    private String getAvailabilityStatus(char status) {

        switch (status) {
            case GraphConstants.AVAILABILITY_CODE_FREE:
                return GraphConstants.AVAILABILITY_STATUS_FREE;
            case GraphConstants.AVAILABILITY_CODE_TENTATIVE:
                return GraphConstants.AVAILABILITY_STATUS_TENTATIVE;
            case GraphConstants.AVAILABILITY_CODE_BUSY:
                return GraphConstants.AVAILABILITY_STATUS_BUSY;
            case GraphConstants.AVAILABILITY_CODE_OUT_OF_OFFICE:
                return GraphConstants.AVAILABILITY_STATUS_FREE;
            default:
                return GraphConstants.AVAILABILITY_STATUS_FREE;
        }
    }

    /**
     * Method to get add required interval to given time
     *
     * @param startTimeSlot
     * @param time
     * @return String
     */
    private String addTime(String startTimeSlot, int time) throws ParseException {

        Date startTime = GraphUtils.convertISOFormatStringToDate(startTimeSlot);
        Date endTime = DateUtils.addMinutes(startTime, time);
        return GraphUtils.convertDateToISOFormatString(endTime);
    }

    @EnableMetrics
    public List<Booking> mapResourceScheduleResponse(List<Event> events, ResourceScheduleRequest request)
            throws HostException {
        try {
            List<String> participantEmailList = new ArrayList<>();

            return events.stream().map(event -> {
                event.attendees.stream().forEach(attendee -> {
                    if (!Objects.isNull(attendee.emailAddress) && !StringUtils.isBlank(attendee.emailAddress.address)) {
                        participantEmailList.add(attendee.emailAddress.address);
                    }
                });
                return assembleBooking(event, request.getAuthToken());
            }).collect(Collectors.toList());
        } catch (Exception e) {
            LOGGER.error("Error occured while parsing resourse schedule response.");
            throw new HostException(e.getMessage(), e.getCause());
        }
    }

    /**
     * @param event
     * @return
     * @throws ParseException
     * @throws URISyntaxException
     * @throws UnsupportedEncodingException
     */
    private Booking assembleBooking(Event event, String authToken) {
        Booking booking = new Booking();
        try {
            booking.setStartTime(event.start.dateTime);
            booking.setEndTime(event.end.dateTime);
        } catch (ParseException e) {
            LOGGER.info("Error occured while Parsing dates for booking Id {}", event.id);
        }

        booking.setTimeZone(event.start.timeZone);

        // Parsing body from HTML to Text
        Document htmlBody = Jsoup.parse(event.body.content);
        String bodyText = new HtmlParserUtil().getPlainText(htmlBody);
        booking.setBody(bodyText);
        booking.setNonFormattedBody(event.body.content);
        booking.setSubject(event.subject);
        booking.setIsOrganizer(event.isOrganizer);
        booking.setIsOnlineMeeting(event.isOnlineMeeting);
        booking.setOnlineMeetingProvider(event.onlineMeetingProvider.toString());
        if (Objects.isNull(event.onlineMeeting)) {
            booking.setOnlineMeeting(null);
        } else {
            OnlineMeeting onlineMeeting = new OnlineMeeting();
            onlineMeeting.setJoinUrl(event.onlineMeeting.joinUrl);
            booking.setOnlineMeeting(onlineMeeting);
        }
        booking.setId(event.id);
        booking.setLocation(event.location.displayName);

        booking.setIsOnlineMeeting(event.isOnlineMeeting);
        booking.setiCalUId(event.iCalUId);

        BookingOrganizer organizer = new BookingOrganizer();
        EmailAddress emailAddress =
                new EmailAddress(event.organizer.emailAddress.name, event.organizer.emailAddress.address);
        organizer.setEmail(emailAddress);
        booking.setOrganizer(organizer);

        List<Participant> participants = mapParticipants(event.attendees, event.isCancelled);

        booking.setParticipants(participants);

        if (Boolean.TRUE.equals(event.isCancelled)) {
            booking.setStatus(GraphConstants.MEETING_CANCELLED_STATUS);
        } else if (Boolean.TRUE.equals(event.isOrganizer)) {
            booking.setStatus(GraphConstants.ATTENDEE_RESPONSE_ATTENDING);
        } else if (!Objects.isNull(event.responseStatus)
                && !StringUtils.isBlank(event.responseStatus.response.name())) {
            booking.setStatus(getFormattedParticipantStatus(event.responseStatus.response.toString()));
        } else {
            String userEmail = GraphUtils.getUserEmail(authToken);
            if (userEmail.equals(GraphConstants.EMPTY)) {
                booking.setStatus(GraphConstants.ATTENDEE_RESPONSE_UNKNOWN);
            } else {
                booking.setStatus(findUserStatus(userEmail, participants));
            }
        }

        booking.setIsRecurring(!StringUtils.isAllBlank(event.seriesMasterId) || !Objects.isNull(event.recurrence));

        booking.setShowAs(event.showAs.toString());
        booking.setIsAllDay(event.isAllDay.toString());

        return booking;
    }

    private String getFormattedParticipantStatus(String status) {
        switch (status.toLowerCase()) {
            case GraphConstants.ATTENDEE_GRAPH_RESPONSE_ACCEPTED:
                return GraphConstants.ATTENDEE_RESPONSE_ATTENDING;
            case GraphConstants.ATTENDEE_GRAPH_RESPONSE_DECLINED:
                return GraphConstants.ATTENDEE_RESPONSE_DECLINED;
            case GraphConstants.ATTENDEE_GRAPH_RESPONSE_SDK_TENTATIVELYACCEPTED:
                return GraphConstants.ATTENDEE_RESPONSE_TENTATIVE;
            case GraphConstants.ATTENDEE_GRAPH_RESPONSE_UNKNOWN:
                return GraphConstants.ATTENDEE_RESPONSE_UNKNOWN;
            case GraphConstants.ATTENDEE_GRAPH_RESPONSE_SDK_NOT_RESPONDED:
                return GraphConstants.ATTENDEE_RESPONSE_UNKNOWN;
            default:
                return GraphConstants.ATTENDEE_RESPONSE_UNKNOWN;
        }
    }

    private List<Participant> mapParticipants(List<Attendee> attendees, boolean isMeetingCancelled) {

        List<Participant> participants = new ArrayList<>();

        for (Attendee attendee : attendees) {
            Participant participant = new Participant();
            participant.setType(attendee.type.toString());
            if (attendee.emailAddress != null) {
                String emailName = attendee.emailAddress.name;
                participant.setEmailAddress(attendee.emailAddress.address);
                participant.setName(emailName);
                participant.setFirstName(emailName);
            }

            // Setting appropriate participant status
            if (isMeetingCancelled) {
                participant.setStatus(GraphConstants.MEETING_CANCELLED_STATUS);
            } else if (!Objects.isNull(attendee.status) && !StringUtils.isBlank(attendee.status.response.toString())) {
                participant.setStatus(getFormattedParticipantStatus(attendee.status.response.toString()));
            } else {
                participant.setStatus(GraphConstants.ATTENDEE_RESPONSE_UNKNOWN);
            }
            if (!Objects.isNull(attendee.status) && !StringUtils.isBlank(attendee.status.response.toString())) {
                participant.setResponseTime(attendee.status.time.toString());
            }
            participants.add(participant);
        }

        return participants;
    }

    private String findUserStatus(String userEmail, List<Participant> participants) {
        for (Participant particpant : participants) {
            if (particpant.getEmailAddress().equalsIgnoreCase(userEmail)) {
                return particpant.getStatus();
            }
        }
        return GraphConstants.ATTENDEE_GRAPH_RESPONSE_UNKNOWN;
    }

    public UserProfile mapUserProfileResponse(User user) {

        UserProfile userProfile = new UserProfile();

        userProfile.setFirstName(user.givenName);
        userProfile.setId(user.id);
        userProfile.setLastName(user.surname);
        userProfile.setEmail(user.userPrincipalName);
        userProfile.setJobTitle(user.jobTitle);
        if (!CollectionUtils.isEmpty(user.businessPhones)) {
            userProfile.setBusinessPhones(user.businessPhones.toArray(new String[user.businessPhones.size()]));
        }
        userProfile.setMobilePhone(user.mobilePhone);
        userProfile.setOfficeLocation(user.officeLocation);
        userProfile.setPreferredLanguage(user.preferredLanguage);
        userProfile.setDepartment(user.department);
        userProfile.setCompanyName(user.companyName);
        userProfile.setCountry(user.country);
        userProfile.setCity(user.city);
        userProfile.setPostalCode(user.postalCode);
        userProfile.setState(user.state);
        userProfile.setStreetAddress(user.streetAddress);
        OnPremisesExtensionAttributes onPremisesExtensionAttr = user.onPremisesExtensionAttributes;
        // Set the Employee id from extension attributes
        if (onPremisesExtensionAttr != null) {
            userProfile.setEmployeeId(onPremisesExtensionAttr.extensionAttribute1);
        }
        return userProfile;
    }

    public Manager mapManagerProfileResponse(DirectoryObject directoryObject) {
        User user = (User) directoryObject;
        Manager manager = new Manager();
        BeanUtils.copyProperties(user, manager);
        if (!CollectionUtils.isEmpty(user.businessPhones)) {
            manager.setBusinessPhones(user.businessPhones.toArray(new String[user.businessPhones.size()]));
        }
        return manager;
    }

    public List<People> maprecommendedPeopleResponse(List<Person> persons) {
        List<People> peoples = new ArrayList<>();
        if (!CollectionUtils.isEmpty(persons)) {
            persons.stream().forEach(person -> {
                People people = new People();
                people.setFirstName(person.givenName);
                people.setEmail(person.userPrincipalName);
                people.setId(person.id);
                people.setLastName(person.surname);
                peoples.add(people);
            });
        }
        return peoples;
    }

    public List<People> mapSearchPeopleResponse(List<User> persons) {
        List<People> peoples = new ArrayList<>();
        if (!CollectionUtils.isEmpty(persons)) {
            persons.stream().forEach(person -> {
                People people = new People();
                people.setFirstName(person.givenName);
                people.setEmail(person.userPrincipalName);
                people.setId(person.id);
                people.setLastName(person.surname);
                peoples.add(people);
            });
        }
        return peoples;
    }

    public List<com.cbre.host.msgraph.dto.Person> mapSearchPersonsResponse(List<User> persons) {
        List<com.cbre.host.msgraph.dto.Person> peoples = new ArrayList<>();
        if (!CollectionUtils.isEmpty(persons)) {
            persons.stream().forEach(person -> {
                com.cbre.host.msgraph.dto.Person people = new com.cbre.host.msgraph.dto.Person();
                people.setDisplayName(person.displayName);
                people.setGivenName(person.givenName);
                people.setId(person.id);
                people.setSurname(person.surname);
                people.setUserPrincipalName(person.userPrincipalName);
                peoples.add(people);
            });
        }
        return peoples;
    }

    @EnableMetrics
    public Booking mapSearchBookingByICalUId(Event event, String authorization) {
        Map<String, com.cbre.host.msgraph.dto.Person> participantDetails = new HashMap<>();
        List<String> participantEmailList = new ArrayList<>();
        event.attendees.stream().forEach(attendee -> {
            if (!Objects.isNull(attendee.emailAddress) && !StringUtils.isBlank(attendee.emailAddress.address)) {
                participantEmailList.add(attendee.emailAddress.address);
            }
        });
        Booking booking = assembleBooking(event, authorization);

        if (!participantEmailList.isEmpty()) {
            participantDetails = fetchParticipantDetails(participantEmailList, authorization);
        }

        for (Participant participant : booking.getParticipants()) {
            // Setting participant details
            if (!participantDetails.isEmpty() && !StringUtils.isBlank(participant.getEmailAddress())
                    && participantDetails.containsKey(participant.getEmailAddress())) {
                participant.setFirstName(participantDetails.get(participant.getEmailAddress()).getGivenName());
                participant.setLastName(participantDetails.get(participant.getEmailAddress()).getSurname());
                participant.setName(participantDetails.get(participant.getEmailAddress()).getDisplayName());
            }
            booking.setIsOnlineMeeting(event.isOnlineMeeting);
            booking.setOnlineMeetingProvider(event.onlineMeetingProvider.toString());
            booking.setiCalUId(event.iCalUId);
            if (Boolean.TRUE.equals(event.isOnlineMeeting)) {
                OnlineMeeting onlineMeeting = new OnlineMeeting();
                onlineMeeting.setJoinUrl(event.onlineMeeting.joinUrl);
                booking.setOnlineMeeting(onlineMeeting);
            }
            booking.setShowAs(event.showAs.toString());
        }

        return booking;
    }

    @EnableMetrics
    public Map<String, com.cbre.host.msgraph.dto.Person> fetchParticipantDetails(List<String> participantList,
            String authToken) {
        HashMap<String, com.cbre.host.msgraph.dto.Person> personMap = new HashMap<>();
        List<com.cbre.host.msgraph.dto.Person> personList = new ArrayList<>();
        List<List<String>> partitionedEmailLists = ListUtils.partition(participantList, 14);

        try {
            partitionedEmailLists.parallelStream().map(partitionedEmailList -> {
                authProvider.setAccessToken(authToken);
                UserCollectionPage page = graphClient.users().buildRequest()
                        .filter(adaptorSdkRequestMapper.mapParticipantDetailsRequest(partitionedEmailList)).get();
                List<com.cbre.host.msgraph.dto.Person> persons = mapSearchPersonsResponse(page.getCurrentPage());
                personList.addAll(persons);
                return personList;
            }).collect(Collectors.toList());
        } catch (Exception e) {
            LOGGER.error("Error occured for Participant List : {}", partitionedEmailLists);
        }
        personList.stream().forEach(person -> personMap.put(person.getUserPrincipalName(), person));
        return personMap;
    }

    @EnableMetrics
    public List<com.cbre.host.msgraph.dto.Event> mapResourceEventsResponse(List<Event> events) throws HostException {
        try {
            List<com.cbre.host.msgraph.dto.Event> eventsList = new ArrayList<>();
            if (!CollectionUtils.isEmpty(events)) {
                events.stream().forEach(e -> {
                    com.cbre.host.msgraph.dto.Event event = new com.cbre.host.msgraph.dto.Event();
                    event.setSubject(e.subject);
                    Body body = new Body();
                    body.setContent(e.body.content);
                    body.setContentType(e.body.contentType.toString());
                    event.setBody(body);
                    DateTimeTimeZone start = new DateTimeTimeZone();
                    start.setDateTime(e.start.dateTime);
                    start.setTimeZone(e.start.timeZone);
                    event.setStart(start);
                    DateTimeTimeZone end = new DateTimeTimeZone();
                    end.setDateTime(e.end.dateTime);
                    end.setTimeZone(e.end.timeZone);
                    event.setEnd(end);
                    event.setId(e.id);
                    EventLocation eventLoc = new EventLocation();
                    eventLoc.setDisplayName(e.location.displayName);
                    eventLoc.setLocationType(e.location.locationType.toString());
                    eventLoc.setUniqueId(e.location.uniqueId);
                    eventLoc.setUniqueIdType(e.location.uniqueIdType.toString());
                    event.setLocation(eventLoc);
                    EventOrganizer eventOrganizer = new EventOrganizer();
                    EmailAddress address =
                            new EmailAddress(e.organizer.emailAddress.name, e.organizer.emailAddress.address);
                    eventOrganizer.setEmailAddress(address);
                    event.setOrganizer(eventOrganizer);
                    event.setIsOrganizer(e.isOrganizer);
                    event.setIsCancelled(e.isCancelled);
                    event.setRecurrence(setEventRecurrencess(e.recurrence));
                    event.setAttendees(mapEventAttendees(e.attendees));
                    event.setSeriesMasterId(e.seriesMasterId);
                    ResponseStatus status = new ResponseStatus();
                    status.setResponse(e.responseStatus.response.toString());
                    event.setResponseStatus(status);
                    event.setShowAs(e.showAs.toString());
                    event.setIsAllDay(e.isAllDay.toString());
                    event.setIsOnlineMeeting(e.isOnlineMeeting);
                    OnlineMeeting onlineMeeting = new OnlineMeeting();
                    onlineMeeting.setJoinUrl(e.onlineMeeting != null ? e.onlineMeeting.joinUrl : null);
                    event.setOnlineMeeting(onlineMeeting);
                    event.setiCalUId(e.iCalUId);
                    eventsList.add(event);
                });
            }

            return eventsList;
        } catch (Exception e) {
            String msg = e.getMessage();
            LOGGER.error("Error occured while parsing resourse-events mapping response:{}", msg);
            throw new HostException(e.getMessage(), e.getCause());
        }
    }

    private EventRecurrence setEventRecurrencess(PatternedRecurrence recurrence) {
        EventRecurrence eventRecurrence = null;
        if (recurrence != null) {
            eventRecurrence = new EventRecurrence();
            EventRecurrencePattern pattern = new EventRecurrencePattern();
            pattern.setDayOfMonth(recurrence.pattern.dayOfMonth);
            pattern.setFirstDayOfWeek(recurrence.pattern.firstDayOfWeek.toString());
            pattern.setIndex(recurrence.pattern.index.toString());
            pattern.setInterval(recurrence.pattern.interval.floatValue());
            pattern.setMonth(recurrence.pattern.month.floatValue());
            pattern.setType(recurrence.pattern.type.toString());
            eventRecurrence.setPatternObj(pattern);

            EventRecurrenceRange range = new EventRecurrenceRange();
            range.setEndDate(recurrence.range.endDate.toString());
            range.setNumberOfOccurrences(recurrence.range.numberOfOccurrences.floatValue());
            range.setRecurrenceTimeZone(recurrence.range.recurrenceTimeZone);
            range.setStartDate(recurrence.range.startDate.toString());
            range.setType(recurrence.range.type.toString());
            eventRecurrence.setRangeObj(range);
        }

        return eventRecurrence;
    }

    private List<EventAttendee> mapEventAttendees(List<Attendee> attendees) {
        List<EventAttendee> list = new ArrayList<>();
        if (!CollectionUtils.isEmpty(attendees)) {
            attendees.parallelStream().forEach(e -> {
                EventAttendee attendee = new EventAttendee();
                attendee.setType(e.type.toString());
                EmailAddress address = new EmailAddress(e.emailAddress.name, e.emailAddress.address);
                EventAttendeeStatus status = new EventAttendeeStatus();
                status.setResponse(e.status.response.toString());
                status.setTime(e.status.time.toString());

                attendee.setEmailAddress(address);
                attendee.setStatus(status);
                list.add(attendee);
            });
        }
        return list;
    }

}

**Comment by criskkan1** [comment]
ok Thank you
