### ISSUE TITLE
ClassNotFoundException reactor.netty.ChannelPipelineConfigurer when using ClientSecretCredentialBuilder with Proxy with v3.3

### ISSUE THREAD

**Issue by b509** [microsoftgraph/msgraph-sdk-java#740]
### Expected behavior
Below code worked with v3.2 and should work with v3.3 as well

### Actual behavior
Getting this error on startup
> Caused by: java.lang.NoClassDefFoundError: reactor/netty/ChannelPipelineConfigurer
	at com.azure.core.http.netty.NettyAsyncHttpClientBuilder.build(NettyAsyncHttpClientBuilder.java:147)
	at com.giam.policyengine.agent.scanner.msgraph.MSGraphClient.getAuthProvider(MSGraphClient.java:186)
	at com.giam.policyengine.agent.scanner.msgraph.MSGraphClient.initGraphClient(MSGraphClient.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 60 common frames omitted
Caused by: java.lang.ClassNotFoundException: reactor.netty.ChannelPipelineConfigurer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 70 common frames omitted

Java version: OpenJDK 11.0.2

### Steps to reproduce the behavior
```java
ClientSecretCredentialBuilder clientCredsBuilder = new ClientSecretCredentialBuilder()
      .clientId(clientId)
      .clientSecret(clientSecret)
      .tenantId(tenant);

// [creation of reactor.netty.http.client.HttpClient httpsClient]

ProxyOptions proxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP, getProxyAddress());

NettyAsyncHttpClientBuilder nettyAsyncHttpClientBuilder =
        httpsClient == null ?
          new NettyAsyncHttpClientBuilder() :
          new NettyAsyncHttpClientBuilder(httpsClient);
HttpClient proxyHttpClient = nettyAsyncHttpClientBuilder.proxy(proxyOptions).build();

clientCredsBuilder.httpClient(proxyHttpClient);
```

Error happens in build method in 
```java
nettyAsyncHttpClientBuilder.proxy(proxyOptions).build();
``` 
[AB#9241](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9241)

**Comment by b509** [comment]
On another environment (AdoptJdk, also Java 11) the error is similar with

"Error creating bean with name 'MSGraphClient': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: reactor/netty/transport/ProxyProvider$TypeSpec"

**Comment by b509** [comment]
This issue
https://github.com/reactor/reactor-netty/issues/1388
looks similar, however the fix "I would recommend to switch to Spring Boot 2.4.0" does not work in my case since because Spring Boot 2.4.0 seems incompatible with Java 11 according to https://thepracticaldeveloper.com/book-update-2.4.0/

**Comment by baywet** [comment]
Hi @b509,
Thanks for reaching out. The `ClientSecretCredentialBuilder` class and related actually belong to [azure-identity](https://github.com/Azure/azure-sdk-for-java). Can you open another issue over there please? The team behind this library will be in a better position to help you.
