### ISSUE TITLE
Upgrading from 1.9.0 to 2.9.0

### ISSUE THREAD

**Issue by ramesharana** [microsoftgraph/msgraph-sdk-java#1152]
I am creating a GraphClient using the following code:

```java
private IGraphServiceClient getGraphClientByClientCredentialGrant(Logger aLogger, String anAuthority,
String anApplicationId, String aSecret, String aScope) throws LambdaLibraryException {

  ConfidentialClientApplication app = ConfidentialClientApplication.builder(
          anApplicationId,
          ClientCredentialFactory.createFromSecret(aSecret))
          .authority(anAuthority)
          .build();

  ClientCredentialParameters clientCredentialParam = ClientCredentialParameters.builder(
          Collections.singleton(aScope))
          .build();

  CompletableFuture<IAuthenticationResult> future = app.acquireToken(clientCredentialParam);
  String myAccessToken = future.get().accessToken();

  theAuthProvider = new SimpleAuthProvider(myAccessToken);

  DefaultLogger myLogger = new DefaultLogger();

  myLogger.setLoggingLevel(LoggerLevel.ERROR);

  IGraphServiceClient myClient = GraphServiceClient.builder()
      .authenticationProvider(theAuthProvider)
      .logger(myLogger)
      .buildClient();

  return myClient;
}
```

This works fine using version 1.9.1 of the SDK. However if I use version 2.9.0 I get the following error:

Method execution failed: 
java.lang.NoSuchMethodError: 'com.microsoft.aad.msal4j.ClientApplicationBase$Builder com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder.authority(java.lang.String)'

All this test is doing is calling the above method with the required parameters to create a new client. I'm guessing that I have missed a changing in the interim releases, but looking at the MS documentation, I can't see what I need to change.

Can someone help?

Thanks,

**Comment by ramesharana** [comment]
we are using the below specific version libraries.
<dependency>
	<groupId>com.microsoft.graph</groupId>
	<artifactId>microsoft-graph</artifactId>
	<version>2.9.0</version>
</dependency>


<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>msal4j</artifactId>
	<version>1.9.1</version>
</dependency>

<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>31.0.1-jre</version>
</dependency>


<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.8.9</version>
</dependency>


<dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	<artifactId>jackson-databind</artifactId>
	<version>2.13.2.2</version>
</dependency>
<dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	<artifactId>jackson-core</artifactId>
	<version>2.13.2</version>
</dependency>
<dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	<artifactId>jackson-annotations</artifactId>
	<version>2.13.2</version>
</dependency> 


<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>1.7.32</version>
</dependency>

**Comment by baywet** [comment]
Hi @ramesharana 
Thanks for reaching out and for using the Java SDK.
We're not supporting the version 2/3/4 of the SDK anymore. Please upgrade straight to version 5.X and let us know if you still run into the issue.
