### ISSUE TITLE
Upgrading from 2.3.1 to 2.8.1 

### ISSUE THREAD

**Issue by AllenConquest** [microsoftgraph/msgraph-sdk-java#672]
I am creating a GraphClient using the following code:

  private IGraphServiceClient getGraphClientByClientCredentialGrant(Logger aLogger, String anAuthority, 
                        String anApplicationId, String aSecret, String aScope) throws LambdaLibraryException {

      ConfidentialClientApplication app = ConfidentialClientApplication.builder(
              anApplicationId,
              ClientCredentialFactory.createFromSecret(aSecret))
              .authority(anAuthority)
              .build();

      ClientCredentialParameters clientCredentialParam = ClientCredentialParameters.builder(
              Collections.singleton(aScope))
              .build();

      CompletableFuture<IAuthenticationResult> future = app.acquireToken(clientCredentialParam);
      String myAccessToken = future.get().accessToken();

      theAuthProvider = new SimpleAuthProvider(myAccessToken);

      DefaultLogger myLogger = new DefaultLogger();

      myLogger.setLoggingLevel(LoggerLevel.ERROR);

      IGraphServiceClient myClient = GraphServiceClient.builder()
          .authenticationProvider(theAuthProvider)
          .logger(myLogger)
          .buildClient();

      return myClient;
}

This works fine using version 2.3.1 of the SDK. However if I use version 2.8.1 I get the following error:

java.lang.NoClassDefFoundError: com/microsoft/graph/httpcore/ICoreAuthenticationProvider
	at com.energysys.pdfconverter.GraphTest.testUpload(GraphTest.java:106)
Caused by: java.lang.ClassNotFoundException: com.microsoft.graph.httpcore.ICoreAuthenticationProvider
	at com.energysys.pdfconverter.GraphTest.testUpload(GraphTest.java:106) 

All this test is doing is calling the above method with the required parameters to create a new client. I'm guessing that I have missed a changing in the interim releases, but looking at the MS documentation, I can't see what I need to change.

Can someone help?

Thanks,

Allen 
[AB#8220](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8220)

**Comment by baywet** [comment]
Hi @AllenConquest 
Thanks for reaching out.
Can you tell me what version of the core library are you using? (`gradle dependencies`)
If you're not on 1.0.8, can you make sure you upgrade and try again please?
Thanks!

**Comment by AllenConquest** [comment]
Hi @baywet 
I am using maven to build the project. My only dependencies were these:

    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>msal4j</artifactId>
      <version>1.7.1</version>
       <type>jar</type>
    </dependency>
    <dependency>
      <groupId>com.microsoft.graph</groupId>
      <artifactId>microsoft-graph</artifactId>
      <version>2.3.1</version>
      <type>jar</type>
    </dependency>

I added in the following dependency:

    <dependency>
      <groupId>com.microsoft.graph</groupId>
      <artifactId>microsoft-graph-core</artifactId>
      <version>1.0.8</version>
      <type>jar</type>
    </dependency>
    <dependency>

and that seems to have solved the problem.

**Comment by baywet** [comment]
thanks for sharing the solution with others. It is strange that maven didn't pull latest from core as you didn't have any other dependency suggesting another version.
